booking:
  property: Booking Profile Dev Update
spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product
              uri: lb://product-microservice
              predicates:
                - Path=/api/product/**, Path=/api/category/**
            - id: booking
              uri: lb://booking-microservice
              predicates:
                - Path=/api/booking/**
          discovery:
            locator:
              enabled: true

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}